-- MySQL Script generated by MySQL Workbench
-- 07/09/14 15:37:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema etuan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `etuan` ;
CREATE SCHEMA IF NOT EXISTS `etuan` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema zentao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zentao` ;
CREATE SCHEMA IF NOT EXISTS `zentao` DEFAULT CHARACTER SET utf8 ;
USE `etuan` ;

-- -----------------------------------------------------
-- Table `etuan`.`organization_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`organization_user` ;

CREATE TABLE IF NOT EXISTS `etuan`.`organization_user` (
  `org_uid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_group` ENUM('root','org') NULL,
  PRIMARY KEY (`org_uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `etuan`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`organization` ;

CREATE TABLE IF NOT EXISTS `etuan`.`organization` (
  `org_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `type` INT NOT NULL,
  `school` VARCHAR(15) NOT NULL,
  `logo_url` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `org_uid` INT NOT NULL,
  PRIMARY KEY (`org_id`),
  INDEX `fk_organization_organization_user1_idx` (`org_uid` ASC),
  CONSTRAINT `fk_organization_organization_user1`
    FOREIGN KEY (`org_uid`)
    REFERENCES `etuan`.`organization_user` (`org_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`department` ;

CREATE TABLE IF NOT EXISTS `etuan`.`department` (
  `depart_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `org_id` INT NOT NULL,
  PRIMARY KEY (`depart_id`),
  INDEX `fk_department_organization1_idx` (`org_id` ASC),
  CONSTRAINT `fk_department_organization1`
    FOREIGN KEY (`org_id`)
    REFERENCES `etuan`.`organization` (`org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`wx_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`wx_user` ;

CREATE TABLE IF NOT EXISTS `etuan`.`wx_user` (
  `wx_uid` VARCHAR(50) NOT NULL,
  `nick_name` VARCHAR(60) NULL,
  `sex` INT NULL,
  `province` VARCHAR(20) NULL,
  `city` VARCHAR(30) NULL,
  `country` VARCHAR(30) NULL,
  `headimgurl` VARCHAR(200) NULL,
  `privilege` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`wx_uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`registration` ;

CREATE TABLE IF NOT EXISTS `etuan`.`registration` (
  `reg_id` INT NOT NULL AUTO_INCREMENT,
  `start_time` VARCHAR(45) NOT NULL,
  `stop_time` VARCHAR(45) NOT NULL,
  `limit_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `theme` INT NOT NULL,
  `url` VARCHAR(15) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `org_uid` INT NOT NULL,
  PRIMARY KEY (`reg_id`),
  INDEX `fk_Registration_organization_user1_idx` (`org_uid` ASC),
  CONSTRAINT `fk_Registration_organization_user1`
    FOREIGN KEY (`org_uid`)
    REFERENCES `etuan`.`organization_user` (`org_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`registration_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`registration_user` ;

CREATE TABLE IF NOT EXISTS `etuan`.`registration_user` (
  `reg_serial` INT NOT NULL AUTO_INCREMENT,
  `used_time` TIME NULL,
  `ip` VARCHAR(50) NULL,
  `student_id` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `reg_id` INT NOT NULL,
  `wx_uid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`reg_serial`),
  INDEX `fk_Registration_user_Registration1_idx` (`reg_id` ASC),
  INDEX `fk_Registration_user_wx_user1_idx` (`wx_uid` ASC),
  CONSTRAINT `fk_Registration_user_Registration1`
    FOREIGN KEY (`reg_id`)
    REFERENCES `etuan`.`registration` (`reg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_user_wx_user1`
    FOREIGN KEY (`wx_uid`)
    REFERENCES `etuan`.`wx_user` (`wx_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`reg_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`reg_question` ;

CREATE TABLE IF NOT EXISTS `etuan`.`reg_question` (
  `reg_id` INT NOT NULL,
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `label` VARCHAR(45) NULL,
  `limit_type` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`question_id`, `reg_id`),
  INDEX `fk_reg_question_Registration1_idx` (`reg_id` ASC),
  CONSTRAINT `fk_reg_question_Registration1`
    FOREIGN KEY (`reg_id`)
    REFERENCES `etuan`.`registration` (`reg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`reg_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`reg_result` ;

CREATE TABLE IF NOT EXISTS `etuan`.`reg_result` (
  `reg_serial` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `answer` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reg_serial`, `question_id`, `answer`),
  INDEX `fk_reg_result_reg_question1_idx` (`question_id` ASC),
  INDEX `fk_reg_result_Registration_user1_idx` (`reg_serial` ASC),
  CONSTRAINT `fk_reg_result_reg_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `etuan`.`reg_question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_result_Registration_user1`
    FOREIGN KEY (`reg_serial`)
    REFERENCES `etuan`.`registration_user` (`reg_serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`reg_question_choice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`reg_question_choice` ;

CREATE TABLE IF NOT EXISTS `etuan`.`reg_question_choice` (
  `reg_id` INT NOT NULL,
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `choice_id` INT NOT NULL,
  `label` VARCHAR(150) NULL,
  PRIMARY KEY (`question_id`, `reg_id`, `choice_id`),
  INDEX `fk_reg_question_choice_reg_question1_idx` (`question_id` ASC),
  INDEX `fk_reg_question_choice_registration1_idx` (`reg_id` ASC),
  CONSTRAINT `fk_reg_question_choice_reg_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `etuan`.`reg_question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_question_choice_registration1`
    FOREIGN KEY (`reg_id`)
    REFERENCES `etuan`.`registration` (`reg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`vote` ;

CREATE TABLE IF NOT EXISTS `etuan`.`vote` (
  `vote_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `stop_time` DATETIME NOT NULL,
  `theme` INT NOT NULL,
  `limit_type` INT NOT NULL,
  `choice_num` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `url` VARCHAR(15) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `org_uid` INT NOT NULL,
  PRIMARY KEY (`vote_id`),
  INDEX `fk_vote_organization_user1_idx` (`org_uid` ASC),
  CONSTRAINT `fk_vote_organization_user1`
    FOREIGN KEY (`org_uid`)
    REFERENCES `etuan`.`organization_user` (`org_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`vote_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`vote_item` ;

CREATE TABLE IF NOT EXISTS `etuan`.`vote_item` (
  `vote_item_id` INT NOT NULL AUTO_INCREMENT,
  `pic_url` VARCHAR(200) NULL,
  `label` VARCHAR(45) NOT NULL,
  `content` VARCHAR(500) NULL,
  `vote_count` INT NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `vote_id` INT NOT NULL,
  PRIMARY KEY (`vote_item_id`, `vote_id`),
  INDEX `fk_vote_item_vote1_idx` (`vote_id` ASC),
  CONSTRAINT `fk_vote_item_vote1`
    FOREIGN KEY (`vote_id`)
    REFERENCES `etuan`.`vote` (`vote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`vote_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`vote_user` ;

CREATE TABLE IF NOT EXISTS `etuan`.`vote_user` (
  `vote_serial` INT NOT NULL AUTO_INCREMENT,
  `used_time` TIME NULL,
  `ip` VARCHAR(50) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `vote_id` INT NOT NULL,
  `wx_uid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`vote_serial`),
  INDEX `fk_vote_user_vote1_idx` (`vote_id` ASC),
  INDEX `fk_vote_user_wx_user1_idx` (`wx_uid` ASC),
  CONSTRAINT `fk_vote_user_vote1`
    FOREIGN KEY (`vote_id`)
    REFERENCES `etuan`.`vote` (`vote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_user_wx_user1`
    FOREIGN KEY (`wx_uid`)
    REFERENCES `etuan`.`wx_user` (`wx_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`vote_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`vote_result` ;

CREATE TABLE IF NOT EXISTS `etuan`.`vote_result` (
  `vote_id` INT NOT NULL,
  `vote_serial` INT NOT NULL,
  `vote_choice` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`vote_id`, `vote_serial`, `vote_choice`),
  INDEX `fk_vote_result_vote1_idx` (`vote_id` ASC),
  INDEX `fk_vote_result_vote_user1_idx` (`vote_serial` ASC),
  CONSTRAINT `fk_vote_result_vote1`
    FOREIGN KEY (`vote_id`)
    REFERENCES `etuan`.`vote` (`vote_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_result_vote_user1`
    FOREIGN KEY (`vote_serial`)
    REFERENCES `etuan`.`vote_user` (`vote_serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`lottery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`lottery` ;

CREATE TABLE IF NOT EXISTS `etuan`.`lottery` (
  `lottery_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `stop_time` DATETIME NOT NULL,
  `theme` INT NOT NULL,
  `limit_type` ENUM('reg','vote','ticket') NOT NULL,
  `activity_id` INT NULL,
  `describion` VARCHAR(200) NULL,
  `url` VARCHAR(15) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `org_uid` INT NOT NULL,
  PRIMARY KEY (`lottery_id`),
  INDEX `fk_lottery_organization_user1_idx` (`org_uid` ASC),
  CONSTRAINT `fk_lottery_organization_user1`
    FOREIGN KEY (`org_uid`)
    REFERENCES `etuan`.`organization_user` (`org_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`lottery_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`lottery_item` ;

CREATE TABLE IF NOT EXISTS `etuan`.`lottery_item` (
  `lottery_item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `probability` INT NOT NULL,
  `item_total` INT NOT NULL,
  `item_out` INT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `lottery_id` INT NOT NULL,
  PRIMARY KEY (`lottery_item_id`),
  INDEX `fk_lottery_item_lottery1_idx` (`lottery_id` ASC),
  CONSTRAINT `fk_lottery_item_lottery1`
    FOREIGN KEY (`lottery_id`)
    REFERENCES `etuan`.`lottery` (`lottery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`lottery_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`lottery_user` ;

CREATE TABLE IF NOT EXISTS `etuan`.`lottery_user` (
  `lottery_serial` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `lottery_id` INT NOT NULL,
  `lottery_item_id` INT NOT NULL,
  `wx_uid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`lottery_serial`),
  INDEX `fk_lottery_user_lottery1_idx` (`lottery_id` ASC),
  INDEX `fk_lottery_user_lottery_item1_idx` (`lottery_item_id` ASC),
  INDEX `fk_lottery_user_wx_user1_idx` (`wx_uid` ASC),
  CONSTRAINT `fk_lottery_user_lottery1`
    FOREIGN KEY (`lottery_id`)
    REFERENCES `etuan`.`lottery` (`lottery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lottery_user_lottery_item1`
    FOREIGN KEY (`lottery_item_id`)
    REFERENCES `etuan`.`lottery_item` (`lottery_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lottery_user_wx_user1`
    FOREIGN KEY (`wx_uid`)
    REFERENCES `etuan`.`wx_user` (`wx_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`mp_weixin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`mp_weixin` ;

CREATE TABLE IF NOT EXISTS `etuan`.`mp_weixin` (
  `mp_id` INT NOT NULL,
  `mp_public_id` VARCHAR(45) NULL,
  `org_uid` INT NULL,
  `interface_url` VARCHAR(200) NULL,
  `interface_token` CHAR(32) NULL,
  PRIMARY KEY (`mp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`mp_auto_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`mp_auto_reply` ;

CREATE TABLE IF NOT EXISTS `etuan`.`mp_auto_reply` (
  `mp_reply_id` INT NOT NULL,
  `mp_id` INT NULL,
  `keyword` VARCHAR(45) NULL,
  PRIMARY KEY (`mp_reply_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`ticket` ;

CREATE TABLE IF NOT EXISTS `etuan`.`ticket` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `act_tittle` VARCHAR(20) NOT NULL,
  `arrange` INT NOT NULL,
  `start_time` DATETIME NULL,
  `logo` VARCHAR(60) NOT NULL,
  `theme` INT NOT NULL,
  `url` VARCHAR(15) NOT NULL,
  `verify` INT NOT NULL,
  `ticket_total` INT NOT NULL,
  `ticket_out` INT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `update_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `org_uid` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_ticket_organization_user1_idx` (`org_uid` ASC),
  CONSTRAINT `fk_ticket_organization_user1`
    FOREIGN KEY (`org_uid`)
    REFERENCES `etuan`.`organization_user` (`org_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`ticket_arrange`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`ticket_arrange` ;

CREATE TABLE IF NOT EXISTS `etuan`.`ticket_arrange` (
  `ticket_id` INT NOT NULL,
  `arrange_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `ticket_total` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ticket_id`, `arrange_id`),
  INDEX `fk_ticket_arrange_ticket1_idx` (`ticket_id` ASC),
  CONSTRAINT `fk_ticket_arrange_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `etuan`.`ticket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etuan`.`ticket_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etuan`.`ticket_result` ;

CREATE TABLE IF NOT EXISTS `etuan`.`ticket_result` (
  `wx_uid` VARCHAR(50) NOT NULL,
  `ticket_id` INT NOT NULL,
  `verify_info` VARCHAR(45) NULL,
  `ip` VARCHAR(50) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`wx_uid`, `ticket_id`),
  INDEX `fk_ticket_result_wx_user1_idx` (`wx_uid` ASC),
  CONSTRAINT `fk_ticket_result_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `etuan`.`ticket` (`ticket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_result_wx_user1`
    FOREIGN KEY (`wx_uid`)
    REFERENCES `etuan`.`wx_user` (`wx_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `zentao` ;

-- -----------------------------------------------------
-- Table `zentao`.`zt_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_action` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_action` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `objectType` VARCHAR(30) NOT NULL DEFAULT '',
  `objectID` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `product` VARCHAR(255) NOT NULL,
  `project` MEDIUMINT(9) NOT NULL,
  `actor` VARCHAR(30) NOT NULL DEFAULT '',
  `action` VARCHAR(30) NOT NULL DEFAULT '',
  `date` DATETIME NOT NULL,
  `comment` TEXT NOT NULL,
  `extra` VARCHAR(255) NOT NULL,
  `read` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 112
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_bug`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_bug` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_bug` (
  `id` MEDIUMINT(8) NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `module` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `project` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `plan` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `story` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `storyVersion` SMALLINT(6) NOT NULL DEFAULT '1',
  `task` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `toTask` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `toStory` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `title` VARCHAR(255) NOT NULL,
  `keywords` VARCHAR(255) NOT NULL,
  `severity` TINYINT(4) NOT NULL DEFAULT '0',
  `pri` TINYINT(3) UNSIGNED NOT NULL,
  `type` VARCHAR(30) NOT NULL DEFAULT '',
  `os` VARCHAR(30) NOT NULL DEFAULT '',
  `browser` VARCHAR(30) NOT NULL DEFAULT '',
  `hardware` VARCHAR(30) NOT NULL,
  `found` VARCHAR(30) NOT NULL DEFAULT '',
  `steps` TEXT NOT NULL,
  `status` ENUM('active','resolved','closed') NOT NULL DEFAULT 'active',
  `confirmed` TINYINT(1) NOT NULL DEFAULT '0',
  `activatedCount` SMALLINT(6) NOT NULL,
  `mailto` VARCHAR(255) NOT NULL DEFAULT '',
  `openedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `openedDate` DATETIME NOT NULL,
  `openedBuild` VARCHAR(255) NOT NULL,
  `assignedTo` VARCHAR(30) NOT NULL DEFAULT '',
  `assignedDate` DATETIME NOT NULL,
  `resolvedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `resolution` VARCHAR(30) NOT NULL DEFAULT '',
  `resolvedBuild` VARCHAR(30) NOT NULL DEFAULT '',
  `resolvedDate` DATETIME NOT NULL,
  `closedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `closedDate` DATETIME NOT NULL,
  `duplicateBug` MEDIUMINT(8) UNSIGNED NOT NULL,
  `linkBug` VARCHAR(255) NOT NULL,
  `case` MEDIUMINT(8) UNSIGNED NOT NULL,
  `caseVersion` SMALLINT(6) NOT NULL DEFAULT '1',
  `result` MEDIUMINT(8) UNSIGNED NOT NULL,
  `lastEditedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `lastEditedDate` DATETIME NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_build`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_build` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_build` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `project` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` CHAR(150) NOT NULL,
  `scmPath` CHAR(255) NOT NULL,
  `filePath` CHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `stories` TEXT NOT NULL,
  `bugs` TEXT NOT NULL,
  `builder` CHAR(30) NOT NULL DEFAULT '',
  `desc` TEXT NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_burn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_burn` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_burn` (
  `project` MEDIUMINT(8) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `left` FLOAT NOT NULL,
  `consumed` FLOAT NOT NULL,
  PRIMARY KEY (`project`, `date`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_case` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_case` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `module` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `path` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `story` MEDIUMINT(30) UNSIGNED NOT NULL DEFAULT '0',
  `storyVersion` SMALLINT(6) NOT NULL DEFAULT '1',
  `title` VARCHAR(255) NOT NULL,
  `precondition` TEXT NOT NULL,
  `keywords` VARCHAR(255) NOT NULL,
  `pri` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3',
  `type` CHAR(30) NOT NULL DEFAULT '1',
  `stage` VARCHAR(255) NOT NULL,
  `howRun` VARCHAR(30) NOT NULL,
  `scriptedBy` VARCHAR(30) NOT NULL,
  `scriptedDate` DATE NOT NULL,
  `scriptStatus` VARCHAR(30) NOT NULL,
  `scriptLocation` VARCHAR(255) NOT NULL,
  `status` CHAR(30) NOT NULL DEFAULT '1',
  `frequency` ENUM('1','2','3') NOT NULL DEFAULT '1',
  `order` TINYINT(30) UNSIGNED NOT NULL DEFAULT '0',
  `openedBy` CHAR(30) NOT NULL DEFAULT '',
  `openedDate` DATETIME NOT NULL,
  `lastEditedBy` CHAR(30) NOT NULL DEFAULT '',
  `lastEditedDate` DATETIME NOT NULL,
  `version` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `linkCase` VARCHAR(255) NOT NULL,
  `fromBug` MEDIUMINT(8) UNSIGNED NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  `lastRunner` VARCHAR(30) NOT NULL,
  `lastRunDate` DATETIME NOT NULL,
  `lastRunResult` CHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_casestep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_casestep` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_casestep` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `case` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `version` SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `desc` TEXT NOT NULL,
  `expect` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `case` (`case` ASC, `version` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_company` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_company` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(120) NULL DEFAULT NULL,
  `phone` CHAR(20) NULL DEFAULT NULL,
  `fax` CHAR(20) NULL DEFAULT NULL,
  `address` CHAR(120) NULL DEFAULT NULL,
  `zipcode` CHAR(10) NULL DEFAULT NULL,
  `website` CHAR(120) NULL DEFAULT NULL,
  `backyard` CHAR(120) NULL DEFAULT NULL,
  `guest` ENUM('1','0') NOT NULL DEFAULT '0',
  `admins` CHAR(255) NULL DEFAULT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_config` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_config` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner` CHAR(30) NOT NULL DEFAULT '',
  `module` VARCHAR(30) NOT NULL,
  `section` CHAR(30) NOT NULL DEFAULT '',
  `key` CHAR(30) NOT NULL DEFAULT '',
  `value` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique` (`owner` ASC, `module` ASC, `section` ASC, `key` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_dept` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_dept` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(60) NOT NULL,
  `parent` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `path` CHAR(255) NOT NULL DEFAULT '',
  `grade` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `order` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `position` CHAR(30) NOT NULL DEFAULT '',
  `function` CHAR(255) NOT NULL DEFAULT '',
  `manager` CHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_doc` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_doc` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL,
  `project` MEDIUMINT(8) UNSIGNED NOT NULL,
  `lib` VARCHAR(30) NOT NULL,
  `module` VARCHAR(30) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `digest` VARCHAR(255) NOT NULL,
  `keywords` VARCHAR(255) NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  `content` TEXT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `views` SMALLINT(5) UNSIGNED NOT NULL,
  `addedBy` VARCHAR(30) NOT NULL,
  `addedDate` DATETIME NOT NULL,
  `editedBy` VARCHAR(30) NOT NULL,
  `editedDate` DATETIME NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_doclib`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_doclib` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_doclib` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_effort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_effort` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_effort` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` CHAR(30) NOT NULL DEFAULT '',
  `todo` ENUM('1','0') NOT NULL DEFAULT '1',
  `date` DATE NOT NULL DEFAULT '0000-00-00',
  `begin` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `type` ENUM('1','2','3') NOT NULL DEFAULT '1',
  `idvalue` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` CHAR(30) NOT NULL DEFAULT '',
  `desc` CHAR(255) NOT NULL DEFAULT '',
  `status` ENUM('1','2','3') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `user` (`user` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_extension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_extension` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_extension` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `code` VARCHAR(30) NOT NULL,
  `version` VARCHAR(50) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `desc` TEXT NOT NULL,
  `license` TEXT NOT NULL,
  `type` VARCHAR(20) NOT NULL DEFAULT 'extension',
  `site` VARCHAR(150) NOT NULL,
  `zentaoCompatible` VARCHAR(100) NOT NULL,
  `installedTime` DATETIME NOT NULL,
  `depends` VARCHAR(100) NOT NULL,
  `dirs` TEXT NOT NULL,
  `files` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code` (`code` ASC),
  INDEX `name` (`name` ASC),
  INDEX `addedTime` (`installedTime` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_file` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_file` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pathname` CHAR(50) NOT NULL,
  `title` CHAR(90) NOT NULL,
  `extension` CHAR(30) NOT NULL,
  `size` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `objectType` CHAR(30) NOT NULL,
  `objectID` MEDIUMINT(9) NOT NULL,
  `addedBy` CHAR(30) NOT NULL DEFAULT '',
  `addedDate` DATETIME NOT NULL,
  `downloads` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `extra` VARCHAR(255) NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_group` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_group` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(30) NOT NULL,
  `role` CHAR(30) NOT NULL DEFAULT '',
  `desc` CHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_grouppriv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_grouppriv` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_grouppriv` (
  `group` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `module` CHAR(30) NOT NULL DEFAULT '',
  `method` CHAR(30) NOT NULL DEFAULT '',
  UNIQUE INDEX `group` (`group` ASC, `module` ASC, `method` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_history` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_history` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `action` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `field` VARCHAR(30) NOT NULL DEFAULT '',
  `old` TEXT NOT NULL,
  `new` TEXT NOT NULL,
  `diff` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_lang` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_lang` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang` VARCHAR(30) NOT NULL,
  `module` VARCHAR(30) NOT NULL,
  `section` VARCHAR(30) NOT NULL,
  `key` VARCHAR(60) NOT NULL,
  `value` TEXT NOT NULL,
  `system` ENUM('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lang` (`lang` ASC, `module` ASC, `section` ASC, `key` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_module` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_module` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `root` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` CHAR(60) NOT NULL DEFAULT '',
  `parent` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `path` CHAR(255) NOT NULL DEFAULT '',
  `grade` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `order` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `type` CHAR(30) NOT NULL,
  `owner` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_product` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_product` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT '',
  `desc` TEXT NOT NULL,
  `PO` VARCHAR(30) NOT NULL,
  `QD` VARCHAR(30) NOT NULL,
  `RD` VARCHAR(30) NOT NULL,
  `acl` ENUM('open','private','custom') NOT NULL DEFAULT 'open',
  `whitelist` VARCHAR(255) NOT NULL,
  `createdBy` VARCHAR(30) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `createdVersion` VARCHAR(20) NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_productplan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_productplan` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_productplan` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL,
  `title` VARCHAR(90) NOT NULL,
  `desc` TEXT NOT NULL,
  `begin` DATE NOT NULL,
  `end` DATE NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_project` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_project` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `isCat` ENUM('1','0') NOT NULL DEFAULT '0',
  `catID` MEDIUMINT(8) UNSIGNED NOT NULL,
  `type` VARCHAR(20) NOT NULL DEFAULT 'sprint',
  `parent` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(90) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `begin` DATE NOT NULL,
  `end` DATE NOT NULL,
  `days` SMALLINT(5) UNSIGNED NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `statge` ENUM('1','2','3','4','5') NOT NULL DEFAULT '1',
  `pri` ENUM('1','2','3','4') NOT NULL DEFAULT '1',
  `desc` TEXT NOT NULL,
  `openedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `openedDate` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `openedVersion` VARCHAR(20) NOT NULL,
  `closedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `closedDate` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `canceledBy` VARCHAR(30) NOT NULL DEFAULT '',
  `canceledDate` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `PO` VARCHAR(30) NOT NULL DEFAULT '',
  `PM` VARCHAR(30) NOT NULL DEFAULT '',
  `QD` VARCHAR(30) NOT NULL DEFAULT '',
  `RD` VARCHAR(30) NOT NULL DEFAULT '',
  `team` VARCHAR(30) NOT NULL,
  `acl` ENUM('open','private','custom') NOT NULL DEFAULT 'open',
  `whitelist` VARCHAR(255) NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `project` (`type` ASC, `parent` ASC, `begin` ASC, `end` ASC, `status` ASC, `statge` ASC, `pri` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_projectproduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_projectproduct` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_projectproduct` (
  `project` MEDIUMINT(8) UNSIGNED NOT NULL,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`project`, `product`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_projectstory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_projectstory` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_projectstory` (
  `project` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `product` MEDIUMINT(8) UNSIGNED NOT NULL,
  `story` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `version` SMALLINT(6) NOT NULL DEFAULT '1',
  UNIQUE INDEX `project` (`project` ASC, `story` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_release`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_release` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_release` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `build` MEDIUMINT(8) UNSIGNED NOT NULL,
  `name` CHAR(30) NOT NULL DEFAULT '',
  `date` DATE NOT NULL,
  `stories` TEXT NOT NULL,
  `bugs` TEXT NOT NULL,
  `desc` TEXT NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_story` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_story` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `module` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `plan` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `source` VARCHAR(20) NOT NULL,
  `fromBug` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `title` VARCHAR(255) NOT NULL,
  `keywords` VARCHAR(255) NOT NULL,
  `type` VARCHAR(30) NOT NULL DEFAULT '',
  `pri` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3',
  `estimate` FLOAT UNSIGNED NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT '',
  `stage` VARCHAR(30) NOT NULL,
  `mailto` VARCHAR(255) NOT NULL DEFAULT '',
  `openedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `openedDate` DATETIME NOT NULL,
  `assignedTo` VARCHAR(30) NOT NULL DEFAULT '',
  `assignedDate` DATETIME NOT NULL,
  `lastEditedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `lastEditedDate` DATETIME NOT NULL,
  `reviewedBy` VARCHAR(255) NOT NULL,
  `reviewedDate` DATE NOT NULL,
  `closedBy` VARCHAR(30) NOT NULL DEFAULT '',
  `closedDate` DATETIME NOT NULL,
  `closedReason` VARCHAR(30) NOT NULL,
  `toBug` MEDIUMINT(9) NOT NULL,
  `childStories` VARCHAR(255) NOT NULL,
  `linkStories` VARCHAR(255) NOT NULL,
  `duplicateStory` MEDIUMINT(8) UNSIGNED NOT NULL,
  `version` SMALLINT(6) NOT NULL DEFAULT '1',
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `product` (`product` ASC, `module` ASC, `plan` ASC, `type` ASC, `pri` ASC),
  INDEX `status` (`status` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_storyspec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_storyspec` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_storyspec` (
  `story` MEDIUMINT(9) NOT NULL,
  `version` SMALLINT(6) NOT NULL,
  `title` VARCHAR(90) NOT NULL,
  `spec` TEXT NOT NULL,
  `verify` TEXT NOT NULL,
  UNIQUE INDEX `story` (`story` ASC, `version` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_task` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_task` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `project` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `module` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `story` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `storyVersion` SMALLINT(6) NOT NULL DEFAULT '1',
  `fromBug` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `pri` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `estimate` FLOAT UNSIGNED NOT NULL,
  `consumed` FLOAT UNSIGNED NOT NULL,
  `left` FLOAT UNSIGNED NOT NULL,
  `deadline` DATE NOT NULL,
  `status` ENUM('wait','doing','done','cancel','closed') NOT NULL DEFAULT 'wait',
  `statusCustom` TINYINT(3) UNSIGNED NOT NULL,
  `mailto` VARCHAR(255) NOT NULL DEFAULT '',
  `desc` TEXT NOT NULL,
  `openedBy` VARCHAR(30) NOT NULL,
  `openedDate` DATETIME NOT NULL,
  `assignedTo` VARCHAR(30) NOT NULL,
  `assignedDate` DATETIME NOT NULL,
  `estStarted` DATE NOT NULL,
  `realStarted` DATE NOT NULL,
  `finishedBy` VARCHAR(30) NOT NULL,
  `finishedDate` DATETIME NOT NULL,
  `canceledBy` VARCHAR(30) NOT NULL,
  `canceledDate` DATETIME NOT NULL,
  `closedBy` VARCHAR(30) NOT NULL,
  `closedDate` DATETIME NOT NULL,
  `closedReason` VARCHAR(30) NOT NULL,
  `lastEditedBy` VARCHAR(30) NOT NULL,
  `lastEditedDate` DATETIME NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `statusOrder` (`statusCustom` ASC),
  INDEX `type` (`type` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_taskestimate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_taskestimate` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_taskestimate` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `task` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `date` DATE NOT NULL,
  `left` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `consumed` FLOAT UNSIGNED NOT NULL,
  `account` CHAR(30) NOT NULL DEFAULT '',
  `work` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `task` (`task` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_team` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_team` (
  `project` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `account` CHAR(30) NOT NULL DEFAULT '',
  `role` CHAR(30) NOT NULL DEFAULT '',
  `join` DATE NOT NULL DEFAULT '0000-00-00',
  `days` SMALLINT(5) UNSIGNED NOT NULL,
  `hours` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`project`, `account`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_testresult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_testresult` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_testresult` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `run` MEDIUMINT(8) UNSIGNED NOT NULL,
  `case` MEDIUMINT(8) UNSIGNED NOT NULL,
  `version` SMALLINT(5) UNSIGNED NOT NULL,
  `caseResult` CHAR(30) NOT NULL,
  `stepResults` TEXT NOT NULL,
  `lastRunner` VARCHAR(30) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `run` (`run` ASC),
  INDEX `case` (`case` ASC, `version` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_testrun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_testrun` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_testrun` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `task` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `case` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `version` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `assignedTo` CHAR(30) NOT NULL DEFAULT '',
  `lastRunner` VARCHAR(30) NOT NULL,
  `lastRunDate` DATETIME NOT NULL,
  `lastRunResult` CHAR(30) NOT NULL,
  `status` CHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `task` (`task` ASC, `case` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_testtask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_testtask` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_testtask` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(90) NOT NULL,
  `product` MEDIUMINT(8) UNSIGNED NOT NULL,
  `project` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `build` CHAR(30) NOT NULL,
  `owner` VARCHAR(30) NOT NULL,
  `pri` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `begin` DATE NOT NULL,
  `end` DATE NOT NULL,
  `desc` TEXT NOT NULL,
  `report` TEXT NOT NULL,
  `status` CHAR(30) NOT NULL,
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_todo` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_todo` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` CHAR(30) NOT NULL,
  `date` DATE NOT NULL DEFAULT '0000-00-00',
  `begin` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL,
  `end` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL,
  `type` CHAR(10) NOT NULL,
  `idvalue` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `pri` TINYINT(3) UNSIGNED NOT NULL,
  `name` CHAR(150) NOT NULL,
  `desc` TEXT NOT NULL,
  `status` CHAR(20) NOT NULL DEFAULT '',
  `private` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user` (`account` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_user` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_user` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dept` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `account` CHAR(30) NOT NULL DEFAULT '',
  `password` CHAR(32) NOT NULL DEFAULT '',
  `role` CHAR(10) NOT NULL DEFAULT '',
  `realname` CHAR(30) NOT NULL DEFAULT '',
  `nickname` CHAR(60) NOT NULL DEFAULT '',
  `commiter` VARCHAR(100) NOT NULL,
  `avatar` CHAR(30) NOT NULL DEFAULT '',
  `birthday` DATE NOT NULL DEFAULT '0000-00-00',
  `gender` ENUM('f','m') NOT NULL DEFAULT 'f',
  `email` CHAR(90) NOT NULL DEFAULT '',
  `skype` CHAR(90) NOT NULL DEFAULT '',
  `qq` CHAR(20) NOT NULL DEFAULT '',
  `yahoo` CHAR(90) NOT NULL DEFAULT '',
  `gtalk` CHAR(90) NOT NULL DEFAULT '',
  `wangwang` CHAR(90) NOT NULL DEFAULT '',
  `mobile` CHAR(11) NOT NULL DEFAULT '',
  `phone` CHAR(20) NOT NULL DEFAULT '',
  `address` CHAR(120) NOT NULL DEFAULT '',
  `zipcode` CHAR(10) NOT NULL DEFAULT '',
  `join` DATE NOT NULL DEFAULT '0000-00-00',
  `visits` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ip` CHAR(15) NOT NULL DEFAULT '',
  `last` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `fails` TINYINT(5) NOT NULL DEFAULT '0',
  `locked` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `deleted` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account` (`account` ASC),
  INDEX `dept` (`dept` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_usercontact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_usercontact` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_usercontact` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` CHAR(30) NOT NULL,
  `listName` VARCHAR(60) NOT NULL,
  `userList` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_usergroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_usergroup` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_usergroup` (
  `account` CHAR(30) NOT NULL DEFAULT '',
  `group` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  UNIQUE INDEX `account` (`account` ASC, `group` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_userquery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_userquery` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_userquery` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` CHAR(30) NOT NULL,
  `module` VARCHAR(30) NOT NULL,
  `title` VARCHAR(90) NOT NULL,
  `form` TEXT NOT NULL,
  `sql` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `account` (`account` ASC),
  INDEX `module` (`module` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `zentao`.`zt_usertpl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zentao`.`zt_usertpl` ;

CREATE TABLE IF NOT EXISTS `zentao`.`zt_usertpl` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` CHAR(30) NOT NULL,
  `type` CHAR(30) NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `account` (`account` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
